server:
  port: 8770


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bjtest2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 092083


mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: mapping/*.xml
#  type-aliases-package: com.jk